name: Commit Counter
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  count:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch commit count
      id: fetch-count
      uses: advait135/fetch-commit-count@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update README
      id: update-readme
      uses: actions/update-readme@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        readme: README.md
        message: "Update commit count to ${{ steps.fetch-count.outputs.count }}"
